### PR TITLE
Upgraded versions of PHP to 7.4 and Symfony 5

### LINKED ISSUE #7: Add compatibility with Symfony 5 and PHP 7.4
I noticed the project hasn't received maintenance in a while.
If it's not abandoned I'd like to see it being updated to support a newer PHP version as well as a description for how to use it with Symfony 5.

Unfortunately I'm not much of help here, since I have minimal experience with PHP and Symfony, but would like to add FluentD logging to an existing Symfony project.
Thank you!

### PR DESCRIPTION
**Pull request by abame**
# Resolves #7 

This PR adds support for PHP >=7.4 and Symfony 5 as well as updates the phpunit library and tests accordingly.

### CODE REVIEW

**Comment by abame** [comment]
@drAlberT  can you please check this out, see if we can merge it and release a new version

**Comment by drAlberT** [comment]
sorry I have no more write access to this repo. ..can't merge.

@hpatoio maybe you can

**Comment by domis86** [comment]
@abame  thanks for your contribution!

**Comment by domis86** [comment]
done https://github.com/musement/monolog-fluentd-bundle/releases

**Pull request merged**
